# -*- coding: utf-8 -*-
"""ShankarP4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8d0gYmLyCQ92qP9aEj0foBNchFCD8gq
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q kagglehub

import kagglehub
import os

path = kagglehub.dataset_download("himadri07/ciciot2023")

print("Dataset path:", path)

for root, dirs, files in os.walk(path):
    print(root)
    print(files[:10])
    print("-" * 50)

import os

for root, dirs, files in os.walk(path):
    for file in files:
        print(os.path.join(root, file))

import pandas as pd
import glob

csv_files = glob.glob(path + "/**/*.csv", recursive=True)

print("CSV Count:", len(csv_files))
print(csv_files[:5])

df = pd.read_csv(csv_files[0])

print(df.shape)
print(df.head())
print(df.columns.tolist())

import glob

csv_files = glob.glob(path + "/**/*.csv", recursive=True)

print("Total CSV files:", len(csv_files))

for f in csv_files[:20]:
    print(f)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier

df = pd.read_csv(
    "/kaggle/input/ciciot2023/CICIOT23/train/train.csv"
)

df["attack"] = (
    df["label"] != "BenignTraffic"
).astype(int)

X = df.drop(
    columns=[
        "label",
        "attack"
    ]
)

y = df["attack"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

model = XGBClassifier(
    n_estimators=200,
    max_depth=8,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    tree_method="hist",
    eval_metric="logloss",
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

prob = model.predict_proba(X_test)[:,1]

print("Accuracy :", accuracy_score(y_test, pred))
print("Precision:", precision_score(y_test, pred))
print("Recall   :", recall_score(y_test, pred))
print("F1 Score :", f1_score(y_test, pred))
print("ROC AUC  :", roc_auc_score(y_test, prob))

!pip install -q shap

import shap

sample = X_test.sample(
    n=5000,
    random_state=42
)

explainer = shap.TreeExplainer(model)

shap_values = explainer.shap_values(sample)

shap.summary_plot(
    shap_values,
    sample
)

shap_importance = pd.DataFrame(
    {
        "feature": sample.columns,
        "importance": abs(shap_values).mean(axis=0)
    }
)

print(
    shap_importance.sort_values(
        by="importance",
        ascending=False
    ).head(20)
)

attack_prob = model.predict_proba(X_test)[:,1]

trust_score = 1 - attack_prob

trust_df = pd.DataFrame({
    "trust_score": trust_score,
    "attack_probability": attack_prob
})

print(trust_df.head())
print(trust_df.describe())

print(df["attack"].value_counts())

print(df["attack"].value_counts(normalize=True))

attack_prob = model.predict_proba(X_test)[:,1]

def trust_mapper(p):
    if p < 0.2:
        return 1.0
    elif p < 0.4:
        return 0.8
    elif p < 0.6:
        return 0.6
    elif p < 0.8:
        return 0.4
    else:
        return 0.2

trust_score = [trust_mapper(p) for p in attack_prob]

import numpy as np

trust_score = 1 - attack_prob

trust_score = (
    trust_score - trust_score.min()
) / (
    trust_score.max() - trust_score.min()
)

import pandas as pd
import numpy as np

attack_prob = model.predict_proba(X_test)[:,1]

trust_score = 1 - attack_prob

trust_score = (
    trust_score - trust_score.min()
) / (
    trust_score.max() - trust_score.min()
)

trust_df = pd.DataFrame({
    "attack_probability": attack_prob,
    "trust_score": trust_score
})

print(trust_df.head())

print(trust_df["trust_score"].describe())

benign = df[df["label"] == "BenignTraffic"]

attack = df[df["label"] != "BenignTraffic"]

attack_sample = attack.sample(
    n=len(benign),
    random_state=42
)

balanced_df = pd.concat(
    [benign, attack_sample]
)

print(
    balanced_df["label"].value_counts()
)

benign = df[df["label"] == "BenignTraffic"]

attack = df[df["label"] != "BenignTraffic"]

attack_sample = attack.sample(
    n=len(benign),
    random_state=42
)

balanced_df = pd.concat(
    [benign, attack_sample]
)

balanced_df = balanced_df.sample(
    frac=1,
    random_state=42
)

print(balanced_df.shape)

print(balanced_df["label"].value_counts())

balanced_df["attack"] = (
    balanced_df["label"] != "BenignTraffic"
).astype(int)

print(
    balanced_df["attack"].value_counts()
)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier

X = balanced_df.drop(
    columns=["label", "attack"]
)

y = balanced_df["attack"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

model = XGBClassifier(
    n_estimators=200,
    max_depth=8,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    tree_method="hist",
    eval_metric="logloss",
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

prob = model.predict_proba(X_test)[:,1]

print("Accuracy :", accuracy_score(y_test, pred))
print("Precision:", precision_score(y_test, pred))
print("Recall   :", recall_score(y_test, pred))
print("F1 Score :", f1_score(y_test, pred))
print("ROC AUC  :", roc_auc_score(y_test, prob))

import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

num_nodes = 50
comm_range = 0.25

G = nx.random_geometric_graph(
    num_nodes,
    comm_range
)

positions = nx.get_node_attributes(
    G,
    "pos"
)

print("Nodes:", G.number_of_nodes())
print("Edges:", G.number_of_edges())

plt.figure(figsize=(8,8))

nx.draw(
    G,
    positions,
    node_size=100,
    with_labels=True
)

plt.show()

import random

for node in G.nodes():

    G.nodes[node]["trust"] = round(
        random.uniform(0.2,1.0),
        2
    )

for node in list(G.nodes())[:10]:

    print(
        node,
        G.nodes[node]["trust"]
    )

for node in G.nodes():

    if G.nodes[node]["trust"] < 0.4:
        G.nodes[node]["malicious"] = True
    else:
        G.nodes[node]["malicious"] = False

print(
    sum(
        nx.get_node_attributes(
            G,
            "malicious"
        ).values()
    )
)

source = 0
destination = 49

path = nx.shortest_path(
    G,
    source,
    destination
)

print(path)

path = [0, 20, 10, 49]

for node in path:
    print(
        node,
        G.nodes[node]["trust"],
        G.nodes[node]["malicious"]
    )

for u, v in G.edges():

    trust_u = G.nodes[u]["trust"]
    trust_v = G.nodes[v]["trust"]

    avg_trust = (
        trust_u + trust_v
    ) / 2

    G[u][v]["weight"] = 1 / avg_trust

safe_path = nx.shortest_path(
    G,
    source=0,
    target=49,
    weight="weight"
)

print(safe_path)

def route_trust(path):

    scores = []

    for node in path:
        scores.append(
            G.nodes[node]["trust"]
        )

    return sum(scores) / len(scores)

baseline_path = nx.shortest_path(
    G,
    0,
    49
)

safe_path = nx.shortest_path(
    G,
    0,
    49,
    weight="weight"
)

print("Baseline:", baseline_path)
print("Baseline Trust:", route_trust(baseline_path))

print()

print("Trust Aware:", safe_path)
print("Trust Aware:", route_trust(safe_path))

for neighbor in G.neighbors(0):
    print(
        neighbor,
        G.nodes[neighbor]["trust"]
    )

for u, v in G.edges():

    trust_u = G.nodes[u]["trust"]
    trust_v = G.nodes[v]["trust"]

    avg_trust = (
        trust_u + trust_v
    ) / 2

    G[u][v]["weight"] = 1 / (avg_trust ** 4)

safe_path = nx.shortest_path(
    G,
    source=0,
    target=49,
    weight="weight"
)

print(safe_path)

print(
    route_trust(
        safe_path
    )
)

for u, v in G.edges():

    trust_u = G.nodes[u]["trust"]
    trust_v = G.nodes[v]["trust"]

    avg_trust = (
        trust_u + trust_v
    ) / 2

    penalty = 1

    if trust_u < 0.4:
        penalty += 10

    if trust_v < 0.4:
        penalty += 10

    G[u][v]["weight"] = (
        penalty / avg_trust
    )

for neighbor in G.neighbors(0):
    print(neighbor, G.nodes[neighbor]["trust"])

source = 8
destination = 41

baseline_path = nx.shortest_path(
    G,
    source=source,
    target=destination
)

safe_path = nx.shortest_path(
    G,
    source=source,
    target=destination,
    weight="weight"
)

print("Baseline:", baseline_path)
print("Baseline Trust:", route_trust(baseline_path))

print()

print("Trust Aware:", safe_path)
print("Trust Aware:", route_trust(safe_path))

print(
    "Source Trust:",
    G.nodes[source]["trust"]
)

print(
    "Destination Trust:",
    G.nodes[destination]["trust"]
)

from itertools import islice

candidate_routes = list(
    islice(
        nx.shortest_simple_paths(
            G,
            source,
            destination
        ),
        10
    )
)

for i, route in enumerate(candidate_routes):
    print(i + 1, route)

def route_trust(path):

    scores = []

    for node in path:
        scores.append(
            G.nodes[node]["trust"]
        )

    return sum(scores) / len(scores)

def route_fitness(path):

    trust = route_trust(path)

    hop_count = len(path) - 1

    fitness = (
        0.8 * trust
        -
        0.2 * hop_count
    )

    return fitness

results = []

for route in candidate_routes:

    trust = route_trust(route)

    hops = len(route)-1

    fitness = route_fitness(route)

    results.append(
        [
            route,
            trust,
            hops,
            fitness
        ]
    )

for r in results:

    print(r)

best_route = max(
    candidate_routes,
    key=route_fitness
)

print("Best Route:")
print(best_route)

print()

print(
    "Trust:",
    route_trust(best_route)
)

print(
    "Fitness:",
    route_fitness(best_route)
)

import pandas as pd
import random

route_results = []

for route in candidate_routes:

    trust = route_trust(route)

    hops = len(route) - 1

    delay = random.uniform(10, 100)

    pdr = random.uniform(0.8, 1.0)

    route_results.append(
        {
            "route": route,
            "trust": trust,
            "hops": hops,
            "delay": delay,
            "pdr": pdr
        }
    )

results_df = pd.DataFrame(route_results)

results_df["delay_norm"] = (
    results_df["delay"] -
    results_df["delay"].min()
) / (
    results_df["delay"].max() -
    results_df["delay"].min()
)

results_df["hop_norm"] = (
    results_df["hops"] -
    results_df["hops"].min()
) / (
    results_df["hops"].max() -
    results_df["hops"].min()
    + 1e-9
)

results_df["fitness"] = (
    0.4 * results_df["trust"]
    +
    0.3 * results_df["pdr"]
    -
    0.2 * results_df["delay_norm"]
    -
    0.1 * results_df["hop_norm"]
)

results_df = results_df.sort_values(
    by="fitness",
    ascending=False
)

print(results_df[
    [
        "trust",
        "hops",
        "delay",
        "pdr",
        "fitness"
    ]
])

print()

print("Best Route:")
print(results_df.iloc[0]["route"])

print()

print("Best Fitness:")
print(results_df.iloc[0]["fitness"])

best_route = results_df.iloc[0]["route"]

print("Route:", best_route)

print(
    "Trust:",
    route_trust(best_route)
)

print(
    "Hop Count:",
    len(best_route)-1
)

import random

def simulate_route(route, packets=100):

    received = 0

    for _ in range(packets):

        success = True

        for node in route:

            trust = G.nodes[node]["trust"]

            if random.random() > trust:

                success = False
                break

        if success:
            received += 1

    pdr = received / packets

    packet_loss = 1 - pdr

    return pdr, packet_loss

pdr, loss = simulate_route(
    best_route,
    packets=1000
)

print("PDR:", pdr)

print("Packet Loss:", loss)

packet_results = []

for route in candidate_routes:

    trust = route_trust(route)

    hops = len(route) - 1

    pdr, loss = simulate_route(
        route,
        packets=1000
    )

    packet_results.append(
        [
            route,
            trust,
            hops,
            pdr,
            loss
        ]
    )

for r in packet_results:

    print(r)

import pandas as pd

packet_df = pd.DataFrame(
    packet_results,
    columns=[
        "route",
        "trust",
        "hops",
        "pdr",
        "packet_loss"
    ]
)

packet_df = packet_df.sort_values(
    by="pdr",
    ascending=False
)

print(packet_df)

packet_size = 1024

throughputs = []

for route in candidate_routes:

    pdr, loss = simulate_route(
        route,
        packets=1000
    )

    received_packets = pdr * 1000

    throughput = (
        received_packets *
        packet_size
    ) / 1000

    throughputs.append(
        throughput
    )

print(throughputs)

delay_results = []

for route in candidate_routes:

    hops = len(route)-1

    avg_trust = route_trust(route)

    delay = hops / avg_trust

    delay_results.append(
        delay
    )

print(delay_results)

import random
import numpy as np

def abc_fitness(route):

    trust = route_trust(route)

    hops = len(route) - 1

    pdr, loss = simulate_route(
        route,
        packets=1000
    )

    throughput = pdr * 1024

    delay = hops / trust

    delay_norm = delay / 10

    throughput_norm = throughput / 1024

    fitness = (
        0.35 * trust
        +
        0.30 * pdr
        +
        0.20 * throughput_norm
        -
        0.10 * delay_norm
        -
        0.05 * (hops / 10)
    )

    return fitness

food_sources = candidate_routes.copy()

fitness_values = [
    abc_fitness(route)
    for route in food_sources
]

print(fitness_values)

num_iterations = 20

best_route = None
best_fitness = -999

for iteration in range(num_iterations):

    for i in range(len(food_sources)):

        current_route = food_sources[i]

        candidate_route = random.choice(
            candidate_routes
        )

        current_fitness = abc_fitness(
            current_route
        )

        candidate_fitness = abc_fitness(
            candidate_route
        )

        if candidate_fitness > current_fitness:

            food_sources[i] = candidate_route

    current_best = max(
        food_sources,
        key=abc_fitness
    )

    current_best_fitness = abc_fitness(
        current_best
    )

    if current_best_fitness > best_fitness:

        best_fitness = current_best_fitness

        best_route = current_best

print("ABC Best Route:")
print(best_route)

print()

print(
    "ABC Fitness:",
    best_fitness
)

print()

print(
    "ABC Trust:",
    route_trust(best_route)
)

pdr, loss = simulate_route(
    best_route,
    packets=1000
)

print("ABC PDR:", pdr)

print("ABC Loss:", loss)

import matplotlib.pyplot as plt
import shap

plt.figure(figsize=(12,8), dpi=300)

shap.summary_plot(
    shap_values,
    sample,
    show=False
)

plt.tight_layout()

plt.savefig(
    "Figure2_SHAP_Summary.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import matplotlib.pyplot as plt

top_features = (
    shap_importance
    .sort_values(
        by="importance",
        ascending=True
    )
    .tail(10)
)

plt.figure(
    figsize=(10,6),
    dpi=300
)

bars = plt.barh(
    top_features["feature"],
    top_features["importance"]
)

for bar in bars:

    width = bar.get_width()

    plt.text(
        width + 0.02,
        bar.get_y() + bar.get_height()/2,
        f"{width:.3f}",
        va="center"
    )

plt.xlabel("Mean SHAP Importance")
plt.ylabel("Feature")
plt.title("Top 10 Influential Features")

plt.tight_layout()

plt.savefig(
    "Figure3_SHAP_FeatureImportance.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import matplotlib.pyplot as plt

methods = [
    "Shortest Path",
    "Trust-Aware",
    "ABC"
]

pdr_values = [
    0.340,
    0.388,
    0.381
]

plt.figure(
    figsize=(8,6),
    dpi=300
)

bars = plt.bar(
    methods,
    pdr_values
)

for bar in bars:

    height = bar.get_height()

    plt.text(
        bar.get_x()+bar.get_width()/2,
        height+0.005,
        f"{height:.3f}",
        ha="center"
    )

plt.ylabel("Packet Delivery Ratio")
plt.title("PDR Comparison")

plt.tight_layout()

plt.savefig(
    "Figure4_PDR_Comparison.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import matplotlib.pyplot as plt

methods = [
    "Shortest Path",
    "Trust-Aware",
    "ABC"
]

throughput = [
    375.81,
    389.12,
    389.12
]

plt.figure(
    figsize=(8,6),
    dpi=300
)

plt.plot(
    methods,
    throughput,
    marker="o",
    linewidth=2,
    markersize=10
)

for x,y in zip(methods,throughput):

    plt.text(
        x,
        y+2,
        f"{y:.2f}",
        ha="center"
    )

plt.ylabel("Throughput")
plt.title("Throughput Analysis")

plt.grid(True)

plt.tight_layout()

plt.savefig(
    "Figure5_Throughput.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import matplotlib.pyplot as plt

methods = [
    "Shortest Path",
    "Trust-Aware",
    "ABC"
]

delay = [
    4.843,
    4.762,
    4.762
]

plt.figure(
    figsize=(8,6),
    dpi=300
)

for i,val in enumerate(delay):

    plt.plot(
        [i,i],
        [0,val],
        linewidth=3
    )

    plt.scatter(
        i,
        val,
        s=150
    )

    plt.text(
        i,
        val+0.03,
        f"{val:.3f}",
        ha="center"
    )

plt.xticks(
    range(len(methods)),
    methods
)

plt.ylabel("Delay")
plt.title("Delay Comparison")

plt.tight_layout()

plt.savefig(
    "Figure6_Delay.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import numpy as np
import matplotlib.pyplot as plt

categories = [
    "Trust",
    "PDR",
    "Throughput",
    "Delay",
    "Packet Loss"
]

shortest = [
    0.826,
    0.340,
    375.81,
    4.843,
    0.660
]

trust_aware = [
    0.840,
    0.388,
    389.12,
    4.762,
    0.612
]

abc = [
    0.840,
    0.381,
    389.12,
    4.762,
    0.619
]

data = np.array([
    shortest,
    trust_aware,
    abc
])

for col in [3,4]:
    data[:,col] = data[:,col].max() - data[:,col]

mins = data.min(axis=0)
maxs = data.max(axis=0)

norm = (data - mins) / (maxs - mins + 1e-9)

shortest_norm = norm[0].tolist()
trust_norm = norm[1].tolist()
abc_norm = norm[2].tolist()

N = len(categories)

angles = np.linspace(
    0,
    2*np.pi,
    N,
    endpoint=False
).tolist()

angles += angles[:1]

shortest_norm += shortest_norm[:1]
trust_norm += trust_norm[:1]
abc_norm += abc_norm[:1]

fig = plt.figure(
    figsize=(8,8),
    dpi=300
)

ax = plt.subplot(
    111,
    polar=True
)

ax.plot(
    angles,
    shortest_norm,
    linewidth=2,
    label="Shortest Path"
)

ax.fill(
    angles,
    shortest_norm,
    alpha=0.10
)

ax.plot(
    angles,
    trust_norm,
    linewidth=2,
    label="Trust-Aware"
)

ax.fill(
    angles,
    trust_norm,
    alpha=0.10
)

ax.plot(
    angles,
    abc_norm,
    linewidth=2,
    label="ABC"
)

ax.fill(
    angles,
    abc_norm,
    alpha=0.10
)

ax.set_xticks(
    angles[:-1]
)

ax.set_xticklabels(
    categories,
    fontsize=11
)

ax.set_title(
    "Routing Performance Comparison",
    pad=30,
    fontsize=14
)

plt.legend(
    loc="upper right",
    bbox_to_anchor=(1.25,1.15)
)

plt.tight_layout()

plt.savefig(
    "Figure7_RadarChart.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test,
    pred
)

plt.figure(
    figsize=(8,6),
    dpi=300
)

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    cbar=True,
    annot_kws={"size":14}
)

plt.xlabel(
    "Predicted Label",
    fontsize=12
)

plt.ylabel(
    "True Label",
    fontsize=12
)

plt.title(
    "Confusion Matrix",
    fontsize=14
)

plt.tight_layout()

plt.savefig(
    "Figure4_ConfusionMatrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve
from sklearn.metrics import auc

fpr, tpr, _ = roc_curve(
    y_test,
    prob
)

roc_auc = auc(
    fpr,
    tpr
)

plt.figure(
    figsize=(8,6),
    dpi=300
)

plt.plot(
    fpr,
    tpr,
    linewidth=3,
    label=f"AUC = {roc_auc:.4f}"
)

plt.plot(
    [0,1],
    [0,1],
    linestyle="--",
    linewidth=2
)

plt.xlabel(
    "False Positive Rate",
    fontsize=12
)

plt.ylabel(
    "True Positive Rate",
    fontsize=12
)

plt.title(
    "ROC Curve",
    fontsize=14
)

plt.legend(
    loc="lower right"
)

plt.grid(True)

plt.tight_layout()

plt.savefig(
    "Figure5_ROC_Curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score

precision, recall, _ = precision_recall_curve(
    y_test,
    prob
)

ap = average_precision_score(
    y_test,
    prob
)

plt.figure(
    figsize=(8,6),
    dpi=300
)

plt.plot(
    recall,
    precision,
    linewidth=3,
    label=f"AP = {ap:.4f}"
)

plt.xlabel(
    "Recall",
    fontsize=12
)

plt.ylabel(
    "Precision",
    fontsize=12
)

plt.title(
    "Precision-Recall Curve",
    fontsize=14
)

plt.legend(
    loc="lower left"
)

plt.grid(True)

plt.tight_layout()

plt.savefig(
    "Figure6_PR_Curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import matplotlib.pyplot as plt

counts = balanced_df["attack"].value_counts()

plt.figure(
    figsize=(7,7),
    dpi=300
)

plt.pie(
    counts,
    labels=[
        "Benign",
        "Attack"
    ],
    autopct="%1.1f%%"
)

plt.title(
    "Balanced Dataset Distribution"
)

plt.tight_layout()

plt.savefig(
    "Figure1_DatasetDistribution.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

table1 = pd.DataFrame({
    "Property":[
        "Dataset Name",
        "Total Samples",
        "Total Features",
        "Attack Samples",
        "Benign Samples",
        "Attack Classes"
    ],
    "Value":[
        "CICIoT2023",
        len(df),
        df.shape[1]-1,
        (df["label"]!="BenignTraffic").sum(),
        (df["label"]=="BenignTraffic").sum(),
        df["label"].nunique()-1
    ]
})

print(table1)

table1.to_csv(
    "Table1_DatasetDescription.csv",
    index=False
)

table4 = packet_df.copy()

print(table4)

table4.to_csv(
    "Table4_RouteEvaluation.csv",
    index=False
)

table4 = packet_df.copy()

table4["throughput"] = (
    table4["pdr"] * 1024
)

table4["delay"] = (
    table4["hops"] /
    table4["trust"]
)

print(table4)

table4.to_csv(
    "Table4_RouteEvaluation_Full.csv",
    index=False
)

from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        pred,
        digits=4
    )
)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(
    figsize=(12,10),
    dpi=300
)

sns.heatmap(
    X.sample(5000).corr(),
    cmap="coolwarm"
)

plt.tight_layout()

plt.savefig(
    "CorrelationHeatmap.png",
    dpi=300
)

plt.show()

print(type(y))
print(y)

X = balanced_df.drop(
    columns=["label", "attack"]
)

y = balanced_df["attack"]

print(type(y))
print(y.shape)

from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print(scores)

print("Mean Accuracy:", scores.mean())
print("Std Accuracy :", scores.std())

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=15,
    random_state=42,
    n_jobs=-1
)

rf.fit(
    X_train,
    y_train
)

rf_pred = rf.predict(
    X_test
)

rf_prob = rf.predict_proba(
    X_test
)[:,1]

rf_accuracy = accuracy_score(
    y_test,
    rf_pred
)

rf_precision = precision_score(
    y_test,
    rf_pred
)

rf_recall = recall_score(
    y_test,
    rf_pred
)

rf_f1 = f1_score(
    y_test,
    rf_pred
)

rf_auc = roc_auc_score(
    y_test,
    rf_prob
)

print("Accuracy :", rf_accuracy)
print("Precision:", rf_precision)
print("Recall   :", rf_recall)
print("F1 Score :", rf_f1)
print("ROC AUC  :", rf_auc)

import matplotlib.pyplot as plt
import numpy as np

metrics = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1-Score",
    "ROC-AUC"
]

rf_scores = [
    0.9963717770572796,
    0.9999611227742788,
    0.9927821522309711,
    0.9963587061785784,
    0.9994976166422921
]

xgb_scores = [
    0.9970472440944882,
    0.999340804218853,
    0.994750656167979,
    0.9970404472213088,
    0.9996578715283536
]

x = np.arange(len(metrics))

width = 0.35

plt.figure(
    figsize=(11,6),
    dpi=300
)

bars1 = plt.bar(
    x - width/2,
    rf_scores,
    width,
    label="Random Forest"
)

bars2 = plt.bar(
    x + width/2,
    xgb_scores,
    width,
    label="XGBoost"
)

for bar in bars1:

    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 0.00015,
        f"{height:.4f}",
        ha="center",
        fontsize=8,
        rotation=90
    )

for bar in bars2:

    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 0.00015,
        f"{height:.4f}",
        ha="center",
        fontsize=8,
        rotation=90
    )

plt.xticks(
    x,
    metrics,
    fontsize=11
)

plt.ylabel(
    "Performance Score",
    fontsize=12
)

plt.xlabel(
    "Evaluation Metrics",
    fontsize=12
)

plt.title(
    "Performance Comparison of Random Forest and XGBoost Models",
    fontsize=14,
    pad=15
)

plt.ylim(
    0.99,
    1.001
)

plt.legend()

plt.grid(
    axis="y",
    linestyle="--",
    alpha=0.6
)

plt.tight_layout()

plt.savefig(
    "Figure12_RF_vs_XGBoost.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()